#pragma once
#define MAX_NUMBER_OF_ITEMS 5
#define MAX_VELOCITY_PLAYER 2
#define SPRITE_SCALE_PLAYER 0.5
#define MAX_VELOCITY_MONSTER 2
#define SPRITE_SCALE_MONSTER 0.5
#define MAX_VELOCITY_PROJECTILE 1
#define SPRITE_SCALE_PROJECTILE 0.7
#define MAX_MONSTERS 10
#define MAX_PROJECTILES 5
#define WINDOW_SIZE_X 1600
#define WINDOW_SIZE_Y 900
